configs_version: 4

Plugin:
  name: "Oraxen"
  prefix: "&bOraxen &8|&7 "

  commands:
    repair:
      oraxen_durability_only: false # will not repair vanilla items if set to true

Pack:
  generation:
    generate: true
    compression: BEST_COMPRESSION # see Deflater.class
    comment: "The content of this texture pack
     \nbelongs to the owner of the Oraxen
     \nplugin and any complete or partial
     \nuse must comply with the terms and
     \nconditions of Oraxen."

  upload:
    enabled: true
    type: polymath #transfer.sh or polymath
    polymath:
      server: atlas.oraxen.com # you can also host your own polymath instance

  dispatch:
    send_pack: true
    join_message:
      enabled: false
      delay: -1
      content: # you can also use & color codes for simple messages but <balise> mini message formatting is better because
        # it supports custom actions (click, hover, etc) and also multiple lines messages
        - "<dark_gray><strikethrough>                           </strikethrough><dark_gray>{<aqua><bold> Resource Pack </bold><dark_gray>}<dark_gray><strikethrough>                        </strikethrough>"
        - ""
        - "<gray><bold>To see the new items you need to use a special resourcepack (but don't worry, this doesn't prevent you from using yours at the same time).</bold>"
        - ""
        - "<dark_gray>»<gray> To try to load it directly from the game, <click:run_command:/oraxen pack send><hover:show_text:\"<red>/!\\ loading the resourcepack from the game can cause lags\"><red><bold>CLICK HERE</bold></hover></click>"
        - ""
        - "<dark_gray>»<gray> To download it from the internet, <click:open_url:<pack_url>><hover:show_text:\"<green>/!\\ install it from Options/ResourcePacks in your game\"><green><bold>CLICK HERE</bold></hover></click>"

  receive:
    enabled: true

    loaded:
      actions:
        message:
          enabled: true
          # KICK / CHAT / ACTION_BAR / TITLE
          type: ACTION_BAR
          # Delay before the first message to appear, this is in seconds
          delay: 0
          # You only need a period if you send multiple messages of type ACTION_BAR or TITLE
          period: -1
          # Click and Hover elements are only available by using the CHAT type
          messages:
            - "&a&lResourcePack successfully loaded!"

        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    accepted:
      actions:
        message:
          enabled: true
          # KICK / CHAT / ACTION_BAR / TITLE
          type: TITLE
          # Delay before the first message to appear, this is in seconds
          delay: 0
          # You only need a period if you send multiple messages of type ACTION_BAR or TITLE
          period: 3
          # Click and Hover elements are only available by using the CHAT type
          messages:
            - "&a&lResourcePack accepted!"
            - "Thank you"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    denied:
      actions:
        message:
          enabled: true
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Delay before the first message to appear, this is in seconds
          delay: 0
          # You can put any value here because this is a CHAT message
          period: -1
          # Click and Hover elements are only available by using the CHAT type
          messages:
            - "<red>You refused the ResourcePack, but you need it in order to see the new items. Please </red><click:run_command:/oraxen pack get><hover:show_text:\"<green>Display more informations\"><green><bold>CLICK HERE</bold></hover></click> <red>or type <bold>/o pack"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    failed_download:
      actions:
        message:
          enabled: true
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Delay before the first message to appear, this is in seconds
          delay: 0
          # You can put any value here because this is a CHAT message
          period: -1
          # Click and Hover elements are only available by using the CHAT type
          messages:
            - "<red>You failed to download the ResourcePack, but you need it in order to see the new items. Please </red><click:run_command:/oraxen pack get><hover:show_text:\"<red>/!\\ loading the resourcepack from the game can cause lags\"><red><bold>CLICK HERE</bold></hover></click> <red>to retry or type <bold>/o pack</bold> and download it from the internet"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

ConfigsTools:
  # Nice for production servers, automatically set model ID in settings so
  # that you can other items without destroying the others already created
  automatically_set_model_id: false
  enable_configs_updater: true
  error_item:
    material: PODZOL
    excludeFromInventory: false # set to true if you don't want to display it inside inventory
    injectID: false

Misc:
  # If this is set to true, Oraxen will reset recipes on reload. This might create conflicts with other plugins
  # but this makes the things easier if you want to try your oraxen recipes.
  reset_recipes: true

  # All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
  armor_equip_event_bypass:
    - FURNACE
    - CHEST
    - TRAPPED_CHEST
    - BEACON
    - DISPENSER
    - DROPPER
    - HOPPER
    - WORKBENCH
    - ENCHANTMENT_TABLE
    - ENDER_CHEST
    - ANVIL
    - BED_BLOCK
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - ACACIA_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - IRON_DOOR_BLOCK
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - WOOD_BUTTON
    - STONE_BUTTON
    - TRAP_DOOR
    - IRON_TRAPDOOR
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_COMPARATOR_ON
    - FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - NETHER_FENCE
    - BREWING_STAND
    - CAULDRON
    - LEGACY_SIGN_POST
    - LEGACY_WALL_SIGN
    - LEGACY_SIGN
    - ACACIA_SIGN
    - ACACIA_WALL_SIGN
    - BIRCH_SIGN
    - BIRCH_WALL_SIGN
    - DARK_OAK_SIGN
    - DARK_OAK_WALL_SIGN
    - JUNGLE_SIGN
    - JUNGLE_WALL_SIGN
    - OAK_SIGN
    - OAK_WALL_SIGN
    - SPRUCE_SIGN
    - SPRUCE_WALL_SIGN
    - LEVER
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - SILVER_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - DAYLIGHT_DETECTOR_INVERTED
    - DAYLIGHT_DETECTOR
    - BARREL
    - BLAST_FURNACE
    - SMOKER
    - CARTOGRAPHY_TABLE
    - COMPOSTER
    - GRINDSTONE
    - LECTERN
    - LOOM
    - STONECUTTER
    - BELL

  # If you want to add shields, Oraxen needs to setup the display options of the default shield, here are the vanilla ones:
  shield_display: "{\"thirdperson_righthand\":{\"rotation\":[0,90,0],\"translation\":[10,6,-4],\"scale\":[1,1,1]},\"thirdperson_lefthand\":{\"rotation\":[0,90,0],\"translation\":[10,6,12],\"scale\":[1,1,1]},\"firstperson_righthand\":{\"rotation\":[0,180,5],\"translation\":[-10,2,-10],\"scale\":[1.25,1.25,1.25]},\"firstperson_lefthand\":{\"rotation\":[0,180,5],\"translation\":[10,0,-10],\"scale\":[1.25,1.25,1.25]},\"gui\":{\"rotation\":[15,-25,-5],\"translation\":[2,3,0],\"scale\":[0.65,0.65,0.65]},\"fixed\":{\"rotation\":[0,180,0],\"translation\":[-2,4,-5],\"scale\":[0.5,0.5,0.5]},\"ground\":{\"rotation\":[0,0,0],\"translation\":[4,4,2],\"scale\":[0.25,0.25,0.25]}}"

  # Same for bows:
  bow_display: "{\"thirdperson_righthand\":{\"rotation\":[-80,260,-40],\"translation\":[-1,-2,2.5],\"scale\":[0.9,0.9,0.9]},\"thirdperson_lefthand\":{\"rotation\":[-80,-280,40],\"translation\":[-1,-2,2.5],\"scale\":[0.9,0.9,0.9]},\"firstperson_righthand\":{\"rotation\":[0,-90,25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]},\"firstperson_lefthand\":{\"rotation\":[0,90,-25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]}}"

# Better customization for GUI oraxen inv. Oraxen Items Work. its gui_inventory.<name to file without extension yml>
gui_inventory:
  armors: emerald_chestplate
  blocks: orax_ore
  guis: CHEST
  hats: crown
  items: ruby
  mobs: goblin_beetle
  mystical: legendary_hammer
  skins: wood_sword
  tools: iron_serpe
  weapons: energy_crystal_sword
