configs_version: 1

Plugin:
  name: "Oraxen"
  prefix: "&8&l[&bOraxen&8&l] §7"

Pack:
  # Nice for production servers, automatically set model ID in settings so
  # that you can other items without destroying the others already created
  automatically_set_model_id: false
  generation:
    generate: true
    compression: BEST_COMPRESSION # see Deflater.class
    comment: "The content of this texture pack
     \nbelongs to the owner of the Oraxen
     \nplugin and any complete or partial
     \nuse must comply with the terms and
     \nconditions of Oraxen."

  upload:
    enabled: true
    type: polymath #transfer.sh or polymath
    polymath:
      server: atlas.oraxen.com:8080 # you can also host your own polymath instance

  dispatch:
    send_pack: true
    send_welcome_message: false
    welcome_message:
      - "<dark_gray><strikethrough>                           </strikethrough><dark_gray>{<aqua><bold> Resource Pack </bold><dark_gray>}<dark_gray><strikethrough>                        </strikethrough>"
      - ""
      - "<gray><bold>To see the new items you need to use a special resourcepack (but don't worry, this doesn't prevent you from using yours at the same time).</bold>"
      - ""
      - "<dark_gray>»<gray> To try to load it directly from the game, <click:run_command:/oraxen pack getpack><hover:show_text:\"<red>/!\\ loading the resourcepack from the game can cause lags\"><red><bold>CLICK HERE</bold></hover></click>"
      - ""
      - "<dark_gray>»<gray> To download it from the internet, <click:open_url:<pack_url>><hover:show_text:\"<green>/!\\ install it from Options/ResourcePacks in your game\"><green><bold>CLICK HERE</bold></hover></click>"

ConfigsTools:
  enable_configs_updater: true

Misc:
  # All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
  armor_equip_event_bypass:
    - FURNACE
    - CHEST
    - TRAPPED_CHEST
    - BEACON
    - DISPENSER
    - DROPPER
    - HOPPER
    - WORKBENCH
    - ENCHANTMENT_TABLE
    - ENDER_CHEST
    - ANVIL
    - BED_BLOCK
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - ACACIA_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - IRON_DOOR_BLOCK
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - WOOD_BUTTON
    - STONE_BUTTON
    - TRAP_DOOR
    - IRON_TRAPDOOR
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_COMPARATOR_ON
    - FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - NETHER_FENCE
    - BREWING_STAND
    - CAULDRON
    - LEGACY_SIGN_POST
    - LEGACY_WALL_SIGN
    - LEGACY_SIGN
    - ACACIA_SIGN
    - ACACIA_WALL_SIGN
    - BIRCH_SIGN
    - BIRCH_WALL_SIGN
    - DARK_OAK_SIGN
    - DARK_OAK_WALL_SIGN
    - JUNGLE_SIGN
    - JUNGLE_WALL_SIGN
    - OAK_SIGN
    - OAK_WALL_SIGN
    - SPRUCE_SIGN
    - SPRUCE_WALL_SIGN
    - LEVER
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - SILVER_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - DAYLIGHT_DETECTOR_INVERTED
    - DAYLIGHT_DETECTOR
    - BARREL
    - BLAST_FURNACE
    - SMOKER
    - CARTOGRAPHY_TABLE
    - COMPOSTER
    - GRINDSTONE
    - LECTERN
    - LOOM
    - STONECUTTER
    - BELL